name: glamora_project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  calendar_date_picker2: ^1.1.6
  cupertino_icons: ^1.0.8
  day_night_time_picker: ^1.3.1
  email_validator: ^3.0.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  go_router: ^16.2.4
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.2.0
  http: ^1.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true

  image_path_ios: assets/images/app_icon.png
  adaptive_icon_background: assets/images/icon_bg.png
  adaptive_icon_foreground: assets/images/icon_fg.png
